version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/code_pipeline
    overwrite: yes

permissions:
  - object: /
    owner: ubuntu
    group: ubuntu

hooks:
  ApplicationStart:
    - location: /script.sh
      timeout: 900
      runas: root
